# Generated by Django 4.2.3 on 2023-07-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10)),
                ('number', models.PositiveBigIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('profit', models.PositiveIntegerField()),
                ('wage', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_stored', models.PositiveBigIntegerField()),
                ('c_reserved', models.PositiveBigIntegerField()),
                ('c_available', models.PositiveBigIntegerField()),
                ('x_oldest', models.CharField(max_length=10)),
                ('x_youngest', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.product')),
            ],
        ),
    ]
