# Generated by Django 4.2.3 on 2023-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
