# Generated by Django 4.2.3 on 2023-07-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=6, unique=True)),
                ('floor', models.CharField(max_length=1)),
                ('section', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=1)),
                ('shelf', models.CharField(max_length=1)),
                ('column', models.CharField(max_length=1)),
                ('row', models.CharField(max_length=1)),
                ('emc', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=8, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('profit', models.PositiveIntegerField(default=0)),
                ('wage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=6, unique=True)),
                ('prefer', models.CharField(default=0, max_length=8)),
                ('empty', models.BooleanField(default=True)),
                ('reserved', models.BooleanField(default=False)),
                ('age', models.BigIntegerField(default=0)),
                ('product', models.CharField(max_length=8)),
                ('carrier', models.CharField(max_length=20)),
                ('order', models.CharField(max_length=20)),
            ],
        ),
    ]
