# Generated by Django 4.2.3 on 2023-08-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
