# Generated by Django 4.2.3 on 2023-08-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=8, unique=True)),
                ('total_despatched', models.FloatField()),
                ('total_age', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_wage', models.FloatField()),
                ('demand', models.FloatField()),
                ('flow', models.FloatField()),
                ('total_order', models.FloatField()),
            ],
        ),
    ]
