# Generated by Django 4.2.3 on 2023-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=10, unique=True)),
                ('number_of_different_product', models.FloatField()),
                ('received_timestamp', models.TextField()),
                ('despatch_timestamp', models.TextField()),
                ('order_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
