# Generated by Django 4.2.3 on 2023-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_order_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('total_carrier', models.PositiveBigIntegerField()),
                ('total_shelf_age', models.PositiveBigIntegerField()),
                ('total_cost', models.PositiveBigIntegerField()),
                ('total_price', models.PositiveBigIntegerField()),
                ('total_wage', models.PositiveBigIntegerField()),
                ('total_order', models.PositiveBigIntegerField()),
                ('total_different_day_timestamp', models.IntegerField()),
                ('maximum_demand', models.IntegerField()),
                ('average_demand', models.FloatField()),
                ('minimum_demand', models.IntegerField()),
                ('maximum_flow', models.IntegerField()),
                ('average_flow', models.PositiveBigIntegerField()),
                ('minimum_flow', models.IntegerField()),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_different_product',
            field=models.IntegerField(),
        ),
    ]
