# Generated by Django 4.2.3 on 2023-08-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_statistic_alter_order_number_of_different_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='Carrier',
        ),
    ]
