# Generated by Django 4.2.3 on 2023-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_rename_statistic_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('total_carrier', models.PositiveBigIntegerField()),
                ('total_shelf_age', models.PositiveBigIntegerField()),
                ('total_cost', models.PositiveBigIntegerField()),
                ('total_price', models.PositiveBigIntegerField()),
                ('total_wage', models.PositiveBigIntegerField()),
                ('total_order', models.PositiveBigIntegerField()),
                ('total_different_day_timestamp', models.IntegerField()),
                ('maximum_demand', models.IntegerField()),
                ('average_demand', models.FloatField()),
                ('minimum_demand', models.IntegerField()),
                ('maximum_flow', models.IntegerField()),
                ('average_flow', models.PositiveBigIntegerField()),
                ('minimum_flow', models.IntegerField()),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='maximum_demand',
            new_name='shelf_age',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='average_demand',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='average_flow',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='maximum_flow',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='minimum_demand',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='minimum_flow',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_carrier',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_different_day_timestamp',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_order',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_shelf_age',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_wage',
        ),
        migrations.AddField(
            model_name='carrier',
            name='carrier_code',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='despatch_timestamp',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='order_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='stored_timestamp',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrier',
            name='product_code',
            field=models.CharField(max_length=8),
        ),
    ]
