# Generated by Django 4.2.3 on 2023-07-31 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogCarrier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=20)),
                ('receive', models.BooleanField(default=1)),
                ('despatch', models.BooleanField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 7, 49, 34, 909676))),
                ('coordinate', models.CharField(max_length=6)),
                ('product', models.CharField(max_length=8)),
                ('order', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LogOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 7, 49, 34, 862776))),
            ],
        ),
    ]
