# Generated by Django 4.2.3 on 2023-07-31 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=8)),
                ('p_quantity', models.PositiveIntegerField(default=0)),
                ('p_cost', models.PositiveIntegerField(default=0)),
                ('p_wage', models.PositiveIntegerField(default=0)),
                ('p_emc', models.PositiveBigIntegerField(default=0)),
                ('c_total', models.PositiveIntegerField(default=0)),
                ('c_reserved', models.PositiveIntegerField(default=0)),
                ('c_available', models.PositiveIntegerField(default=0)),
                ('t_order', models.PositiveIntegerField(default=0)),
                ('t_day', models.PositiveIntegerField(default=0)),
                ('t_despatch', models.PositiveBigIntegerField(default=0)),
                ('r_frequency', models.FloatField(default=0)),
                ('r_flow', models.FloatField(default=0)),
                ('r_demand', models.FloatField(default=0)),
                ('s_value', models.PositiveBigIntegerField(default=0)),
                ('s_percentage', models.FloatField(default=0)),
                ('s_assign', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=4)),
                ('a_order', models.PositiveIntegerField(default=0)),
                ('a_day', models.PositiveIntegerField(default=0)),
                ('a_despatch', models.PositiveBigIntegerField(default=0)),
                ('a_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='logcarrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 8, 5, 30, 923267)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 8, 5, 30, 892014)),
        ),
    ]
