# Generated by Django 4.2.3 on 2023-07-31 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_recordproduct_statisticproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logorder',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 26, 36, 880821)),
        ),
        migrations.AlterField(
            model_name='logcarrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 26, 36, 967909)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 26, 36, 880821)),
        ),
    ]
