# Generated by Django 4.2.3 on 2023-08-01 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_logorder_timedespatch_alter_logcarrier_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcarrier',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 8, 37, 4, 291877)),
        ),
        migrations.AlterField(
            model_name='logcarrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 8, 37, 4, 291877)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 8, 37, 4, 256857)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 8, 37, 4, 256857)),
        ),
    ]
