# Generated by Django 4.2.3 on 2023-08-01 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_logcarrier_timedespatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcarrier',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 9, 22, 4, 476958)),
        ),
        migrations.AlterField(
            model_name='logcarrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 9, 22, 4, 476958)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 9, 22, 4, 433009)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 9, 22, 4, 433009)),
        ),
    ]
