# Generated by Django 4.2.3 on 2023-08-04 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_alter_logcarrier_timedespatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcarrier',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 17, 28, 32, 229877)),
        ),
        migrations.AlterField(
            model_name='logcarrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 17, 28, 32, 229877)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timedespatch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 17, 28, 32, 188877)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 17, 28, 32, 188877)),
        ),
    ]
